name: Upload Images
on:
  push:
    branches:
      - "release_v*.*.*"
jobs:
  images:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: install QEMU
        uses: docker/setup-qemu-action@v3
      - name: install Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Set version from branch
        run: echo "VERSION=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      - name: Push images
        env:
          ON_PLUGINS: true
        run: |
          make multi-platform-images VERSION=${{ env.VERSION }}
